### ISSUE TITLE
[面試總覽] html + css + js

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/QuestionForMe#11]
### 個人特質

- 你喜歡自我突破嗎 ?
- 你能接受 18 up 嗎 ?
- 你喜歡溝通嗎？

### 任務 and 協作

- 你如何解決你完全不知道的問題？
- 你如何安排你的任務？
- 當你接到一個任務的時候。你會如何和你的設計，後端同仁溝通？
- GIT 是什麼
- HTTP status 狀態碼

### HTML 

- 有用過 html form tag 嗎？form tag 有哪些屬性？各自功能是什麼？
- 有用過哪些 html5 語意化標籤？ 

### Css :

- 有沒有用過 flex
- 有沒有用過 scss 
- 請說出 inline_內聯元素 / block_塊級元素。差別和舉例哪些 tag 是 (不用全部)
- position 有哪些屬性值？說說看各自差異
- `display:none` 和 `visibility: hidden` 的區別
- 請說出以下 css 權重順序
```css
	(1)
 	A.      div{ background-color:blue; }
	B.      body > div{ background-color:yellow; }
	C.      body div span{ background-color:black; }

	(2)
	A.      #blue{ background-color:blue; }
	B.      .red{ background-color:red; }
	C.      div{ background-color:black; }

	(3)
	A.      <link rel="stylesheet" href="style.css" type="text/css">這個引入的CSS檔內定義 body{ font-size:14px; }
	B.      標頭檔內 <style>body{ font-size:20px; }</style>
	C.      在最後 <div id="blue" class="red" style="font-size:50px">1</div>
```

### Js
```js
/*
  * a, b, foo 的值是什麼？
*/  
function output() {
  console.log({a, b, foo: foo()})
    
  var a = 1;
  const b = 2
  function foo() {
    return 3;
  }
}

output();
```	

```js
/*
  * person 的值是什麼？
*/  
const person = { name: "Sunday", age: 21 }
const changeAge = (x = { ...person }) => x.age += 1
const changeAgeAndName = (x = { ...person }) => {
  x.age += 1
  x.name = "Monday"
}

changeAge(person)
changeAgeAndName()
console.log({person})
```
```js
/*
  * 實現一段腳本，得點擊對應鏈接 console 出相應的編號
  * i = ?
*/  
for(var i = 0; i < 5; i++) {
    setTimeout(function() {
        console.log(i);  
    }, 1000);
}
```
```js
/*
  * 怎麼清空 arrayList, 為什麼會用這方法
*/  
var arrayList = ['a','b','c','d','e','f'];
```
```js
/*
  * 1. console.log(obj.prop.getFullname());	
  * 2. console.log(test());
  * 3. 假如要使用 obj.prop.getFullname return `Alice` 會想怎麼做
*/  
var fullname = 'Eric';
var obj = {
   fullname: 'Alice',
	prop: {
		fullname: 'Tina',
		getFullname: function() {
			return this.fullname;
		}
	}
 };

var test = obj.prop.getFullname;
```
### vue

- 請試說 vue 的核心
- 請試說 vue 框架的特性
- 請試說 vue 生命週期
  - DOM渲染在哪個週期中就已經完成？
  - 第一次頁面加載會觸發哪些 hook ?
- vue 組件傳值
- methods vs computed vs watch 
- v-if vs v-show
- 有沒有用過 axios 
- vuex vs no vuex
  - mutation vs actions
